version: '2.3'
services:
  staking-cli: &stakingcli
    image: block.com/staking-cli
    build:
      context: .
      dockerfile: staking-cli-docker/Dockerfile
      args:
        DATA_DIR: "/basicconfig"
        VERSION: master
        SOURCE_CODE: "https://github.com/dachengcheng2022/staking-deposit-cli.git"
        SYMBOL: CLI
    volumes:
      - ./basicconfig:/basicconfig

  ethbase: &ethbase
    image: block.com/gethbase
    build:
      context: .
      dockerfile: execution-docker-base/Dockerfile
      args:
        CONFIG_BASE_DIR: "/basicconfig"
        DATA_DIR: "/execution"
        SOURCE_CODE: "https://github.com/dachengcheng2022/go-ethereum.git"
        VERSION: release_v1.13.4
        SYMBOL: ETH
    volumes:
      - ./basicconfig:/basicconfig 
      - ./execution:/execution
    dns:
      - 8.8.8.8

  beaconbase: &beaconbase
    image: block.com/beaconbase
    build:
      context: .
      dockerfile: consensus-docker-base/Dockerfile
      args:
        CONFIG_BASE_DIR: "/basicconfig"
        VERSION: release-v4.1.1
        SOURCE_CODE: "https://github.com/dachengcheng2022/prysm.git"
        SYMBOL: BEACON
    volumes:
      - ./basicconfig:/basicconfig
    dns:
      - 8.8.8.8
      
  eth: &eth
    image: block.com/geth
    build:
      context: .
      dockerfile: execution-docker/Dockerfile
      args:
        PORT_RPC: 8545
        EXTIP: "190.92.198.117"
        PEER_IP_LIST: "190.92.198.117,47.236.97.218,8.219.234.134"
    volumes:
      - ./execution:/execution
      - ./execution-data:/data-ephemeral
      - ./basicconfig:/basicconfig
    ports:
      - 8551:8551
      - 8545:8545
      - 30303:30303
    depends_on:
      - ethbase
        
  beacon: &beacon-chain
    image: block.com/beacon-chain
    build:
      context: .
      dockerfile: consensus-docker/Dockerfile
      args:
        DATA_DIR: "/consensus"
        HOST_IP: 190.92.198.117
        PEER_IP_LIST: "190.92.198.117,47.236.97.218,8.219.234.134"
        FEE_RECIPIENT: "0xB48F596e6523d98C986e34B42d2a82c25ae6e36B"
    volumes:
      - ./consensus:/consensus
      - ./consensus-data:/data-ephemeral
      - ./basicconfig:/basicconfig
    ports:
      - 4000:4000
      - 3500:3500
      - 8080:8080
      - 13000:13000
      - 12000:12000
      - 6060:6060
      - 7070:7070
    depends_on:
      - beaconbase
    dns:
      - 8.8.8.8
  contract-cli: &contract-cli
    image: block.com/contract-cli
    build:
      context: .
      dockerfile: contract-docker-base/Dockerfile
      args:
        DATA_DIR: "/basicconfig"
        VERSION: master
        SOURCE_CODE: "https://github.com/dachengcheng2022/ethereal"
        SYMBOL: CLI
    volumes:
      - ./basicconfig:/basicconfig
